package WS.Iplay;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Sms service = new Sms();
 * SmsSoap portType = service.getSmsSoap();
 * portType.moForward(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Sms", targetNamespace = "http://iplay.vn/Webservice/Sms", wsdlLocation = "http://iplay.vn/WebService/Sms.asmx?WSDL")
public class Sms extends Service
{

	private final static URL SMS_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(WS.Iplay.Sms.class.getName());

	static
	{
		URL url = null;
		try
		{
			URL baseUrl;
			baseUrl = WS.Iplay.Sms.class.getResource(".");
			url = new URL(baseUrl, "http://iplay.vn/WebService/Sms.asmx?WSDL");
		}
		catch (MalformedURLException e)
		{
			logger.warning("Failed to create URL for the wsdl Location: 'http://iplay.vn/WebService/Sms.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SMS_WSDL_LOCATION = url;
	}

	public Sms(URL wsdlLocation, QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	public Sms()
	{
		super(SMS_WSDL_LOCATION, new QName("http://iplay.vn/Webservice/Sms", "Sms"));
	}

	/**
	 * 
	 * @return returns SmsSoap
	 */
	@WebEndpoint(name = "SmsSoap")
	public SmsSoap getSmsSoap()
	{
		return super.getPort(new QName("http://iplay.vn/Webservice/Sms", "SmsSoap"), SmsSoap.class);
	}

	/**
	 * 
	 * @return returns SmsSoap
	 */
	@WebEndpoint(name = "SmsSoap12")
	public SmsSoap getSmsSoap12()
	{
		return super.getPort(new QName("http://iplay.vn/Webservice/Sms", "SmsSoap12"), SmsSoap.class);
	}

}
