package WS.GetLinkMedia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetMediaSoap", targetNamespace = "http://tempuri.org/")
public interface GetMediaSoap
{

	/**
	 * 
	 * @param mediaID
	 * @param price
	 * @param channelType
	 * @param requestTime
	 * @param msisdn
	 * @param userName
	 * @param password
	 * @param mediaType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetLinkMedia", action = "http://tempuri.org/GetLinkMedia")
	@WebResult(name = "GetLinkMediaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetLinkMedia", targetNamespace = "http://tempuri.org/", className = "WS.GetLinkMedia.GetLinkMedia")
	@ResponseWrapper(localName = "GetLinkMediaResponse", targetNamespace = "http://tempuri.org/", className = "WS.GetLinkMedia.GetLinkMediaResponse")
	public String getLinkMedia(@WebParam(name = "UserName", targetNamespace = "http://tempuri.org/") String userName,
			@WebParam(name = "Password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "MSISDN", targetNamespace = "http://tempuri.org/") String msisdn,
			@WebParam(name = "MediaType", targetNamespace = "http://tempuri.org/") int mediaType,
			@WebParam(name = "MediaID", targetNamespace = "http://tempuri.org/") String mediaID,
			@WebParam(name = "ChannelType", targetNamespace = "http://tempuri.org/") int channelType,
			@WebParam(name = "Price", targetNamespace = "http://tempuri.org/") double price,
			@WebParam(name = "RequestTime", targetNamespace = "http://tempuri.org/") String requestTime);

	/**
	 * 
	 * @param mediaID
	 * @param price
	 * @param channelType
	 * @param requestTime
	 * @param msisdn
	 * @param cateID
	 * @param userName
	 * @param password
	 * @param mediaType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetLinkMediaByCate", action = "http://tempuri.org/GetLinkMediaByCate")
	@WebResult(name = "GetLinkMediaByCateResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetLinkMediaByCate", targetNamespace = "http://tempuri.org/", className = "WS.GetLinkMedia.GetLinkMediaByCate")
	@ResponseWrapper(localName = "GetLinkMediaByCateResponse", targetNamespace = "http://tempuri.org/", className = "WS.GetLinkMedia.GetLinkMediaByCateResponse")
	public String getLinkMediaByCate(@WebParam(name = "UserName", targetNamespace = "http://tempuri.org/") String userName,
			@WebParam(name = "Password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "MSISDN", targetNamespace = "http://tempuri.org/") String msisdn,
			@WebParam(name = "MediaType", targetNamespace = "http://tempuri.org/") int mediaType,
			@WebParam(name = "CateID", targetNamespace = "http://tempuri.org/") int cateID,
			@WebParam(name = "MediaID", targetNamespace = "http://tempuri.org/") String mediaID,
			@WebParam(name = "ChannelType", targetNamespace = "http://tempuri.org/") int channelType,
			@WebParam(name = "Price", targetNamespace = "http://tempuri.org/") double price,
			@WebParam(name = "RequestTime", targetNamespace = "http://tempuri.org/") String requestTime);

}
