package WS.GetLinkMedia;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * GetMedia service = new GetMedia();
 * GetMediaSoap portType = service.getGetMediaSoap();
 * portType.getLinkMedia(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "GetMedia", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://115.146.122.170:8688/GetMedia.asmx?WSDL")
public class GetMedia extends Service
{

	private final static URL GETMEDIA_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(WS.GetLinkMedia.GetMedia.class.getName());

	static
	{
		URL url = null;
		try
		{
			URL baseUrl;
			baseUrl = WS.GetLinkMedia.GetMedia.class.getResource(".");
			url = new URL(baseUrl, "http://115.146.122.170:8688/GetMedia.asmx?WSDL");
		}
		catch (MalformedURLException e)
		{
			logger.warning("Failed to create URL for the wsdl Location: 'http://115.146.122.170:8688/GetMedia.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		GETMEDIA_WSDL_LOCATION = url;
	}

	public GetMedia(URL wsdlLocation, QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	public GetMedia()
	{
		super(GETMEDIA_WSDL_LOCATION, new QName("http://tempuri.org/", "GetMedia"));
	}

	/**
	 * 
	 * @return returns GetMediaSoap
	 */
	@WebEndpoint(name = "GetMediaSoap")
	public GetMediaSoap getGetMediaSoap()
	{
		return super.getPort(new QName("http://tempuri.org/", "GetMediaSoap"), GetMediaSoap.class);
	}

	/**
	 * 
	 * @return returns GetMediaSoap
	 */
	@WebEndpoint(name = "GetMediaSoap12")
	public GetMediaSoap getGetMediaSoap12()
	{
		return super.getPort(new QName("http://tempuri.org/", "GetMediaSoap12"), GetMediaSoap.class);
	}

}
